version: '3.8'

services:
  # Servicio Angular con Nginx
  angular:
    container_name: angular-nginx
    build: ./hello
      # context: ./hello  # Ruta donde está el Dockerfile de Angular
    ports:
      - "80:80"  # Expone el puerto 80 al host
    volumes:
      - ./hello/nginx.conf:/etc/nginx/nginx.conf:ro  # Monta tu configuración personalizada
      - ./hello/dist/hello/browser:/usr/share/nginx/html  # Archivos estáticos generados por Angular. Necesarios para la busqueda de componentes más alla del index. Le retiro el :ro
    depends_on:
      - db  # Opcional, si tienes otros servicios que dependan de Angular (como una API o BD)
  
  # Servicio Django o API (si es relevante)
  api:
    container_name: api
    build:
      context: ./django  # Ruta donde está el código Django
    command: gunicorn helloDocker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=your_secret_key
      - DATABASE_URL=postgres://myuser:mypassword@localhost:5432/vituclim
    depends_on:
      - db

  # Servicio de base de datos
  db:
    container_name: postgre
    image: postgres:latest
    environment:
      POSTGRES_DB: vituclim
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
