# Generated by Django 5.1.4 on 2024-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(default='ºC', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='value',
            field=models.FloatField(default=24.2),
            preserve_default=False,
        ),
    ]
